export const ROUTES = {
  HOME: '/',
  VAULT: '/cofre',
  LOBBY: '/lobby',
  DASHBOARD: '/dashboard',
  PREMIUM: '/premium',
  COACHES: '/coaches',
  PLAYER_PROFILE: '/perfil/:playerId',
  RIOT_PROFILE: '/riot/:gameName/:tagLine',
  RIOT_CONNECT: '/riot/connect',
  RIOT_CALLBACK: '/riot/callback',
  ADMIN_VAULT: '/admin/cofre',
  WALLET: '/carteira',
  ADMIN_WALLET: '/admin/carteira',
  KARMA_PREVIEW: '/karma/preview',
  LOGIN: '/login',
  REGISTER: '/cadastro',
  ONBOARDING: '/onboarding',
} as const;
