-- DUO LOOT - MIGRATION 0003
-- Placeholder preservado para compatibilidade com historico de migrations.
-- O conteudo real foi movido para 022_vault_leaderboard.sql para rodar
-- depois da base inicial e das tabelas do Cofre.
