-- DUO LOOT - MIGRATION 0004
-- Placeholder preservado para compatibilidade com historico de migrations.
-- O conteudo real foi movido para 023_vault_seasons_winners.sql para rodar
-- depois da base inicial e das tabelas do Cofre.
